# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fanny/Téléchargements/HIB

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fanny/Téléchargements/HIB

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fanny/Téléchargements/HIB/CMakeFiles /home/fanny/Téléchargements/HIB/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fanny/Téléchargements/HIB/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HIB.vpk

# Build rule for target.
HIB.vpk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HIB.vpk
.PHONY : HIB.vpk

# fast build rule for target.
HIB.vpk/fast:
	$(MAKE) -f CMakeFiles/HIB.vpk.dir/build.make CMakeFiles/HIB.vpk.dir/build
.PHONY : HIB.vpk/fast

#=============================================================================
# Target rules for targets named HIB.self

# Build rule for target.
HIB.self: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HIB.self
.PHONY : HIB.self

# fast build rule for target.
HIB.self/fast:
	$(MAKE) -f CMakeFiles/HIB.self.dir/build.make CMakeFiles/HIB.self.dir/build
.PHONY : HIB.self/fast

#=============================================================================
# Target rules for targets named HIB

# Build rule for target.
HIB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HIB
.PHONY : HIB

# fast build rule for target.
HIB/fast:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/build
.PHONY : HIB/fast

bullet.obj: bullet.c.obj

.PHONY : bullet.obj

# target to build an object file
bullet.c.obj:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/bullet.c.obj
.PHONY : bullet.c.obj

bullet.i: bullet.c.i

.PHONY : bullet.i

# target to preprocess a source file
bullet.c.i:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/bullet.c.i
.PHONY : bullet.c.i

bullet.s: bullet.c.s

.PHONY : bullet.s

# target to generate assembly for a file
bullet.c.s:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/bullet.c.s
.PHONY : bullet.c.s

display.obj: display.c.obj

.PHONY : display.obj

# target to build an object file
display.c.obj:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/display.c.obj
.PHONY : display.c.obj

display.i: display.c.i

.PHONY : display.i

# target to preprocess a source file
display.c.i:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/display.c.i
.PHONY : display.c.i

display.s: display.c.s

.PHONY : display.s

# target to generate assembly for a file
display.c.s:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/display.c.s
.PHONY : display.c.s

enemy.obj: enemy.c.obj

.PHONY : enemy.obj

# target to build an object file
enemy.c.obj:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/enemy.c.obj
.PHONY : enemy.c.obj

enemy.i: enemy.c.i

.PHONY : enemy.i

# target to preprocess a source file
enemy.c.i:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/enemy.c.i
.PHONY : enemy.c.i

enemy.s: enemy.c.s

.PHONY : enemy.s

# target to generate assembly for a file
enemy.c.s:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/enemy.c.s
.PHONY : enemy.c.s

gui.obj: gui.c.obj

.PHONY : gui.obj

# target to build an object file
gui.c.obj:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/gui.c.obj
.PHONY : gui.c.obj

gui.i: gui.c.i

.PHONY : gui.i

# target to preprocess a source file
gui.c.i:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/gui.c.i
.PHONY : gui.c.i

gui.s: gui.c.s

.PHONY : gui.s

# target to generate assembly for a file
gui.c.s:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/gui.c.s
.PHONY : gui.c.s

input.obj: input.c.obj

.PHONY : input.obj

# target to build an object file
input.c.obj:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/input.c.obj
.PHONY : input.c.obj

input.i: input.c.i

.PHONY : input.i

# target to preprocess a source file
input.c.i:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/input.c.i
.PHONY : input.c.i

input.s: input.c.s

.PHONY : input.s

# target to generate assembly for a file
input.c.s:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/input.c.s
.PHONY : input.c.s

main.obj: main.c.obj

.PHONY : main.obj

# target to build an object file
main.c.obj:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/main.c.obj
.PHONY : main.c.obj

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/main.c.s
.PHONY : main.c.s

ship.obj: ship.c.obj

.PHONY : ship.obj

# target to build an object file
ship.c.obj:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/ship.c.obj
.PHONY : ship.c.obj

ship.i: ship.c.i

.PHONY : ship.i

# target to preprocess a source file
ship.c.i:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/ship.c.i
.PHONY : ship.c.i

ship.s: ship.c.s

.PHONY : ship.s

# target to generate assembly for a file
ship.c.s:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/ship.c.s
.PHONY : ship.c.s

spacestation.obj: spacestation.c.obj

.PHONY : spacestation.obj

# target to build an object file
spacestation.c.obj:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/spacestation.c.obj
.PHONY : spacestation.c.obj

spacestation.i: spacestation.c.i

.PHONY : spacestation.i

# target to preprocess a source file
spacestation.c.i:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/spacestation.c.i
.PHONY : spacestation.c.i

spacestation.s: spacestation.c.s

.PHONY : spacestation.s

# target to generate assembly for a file
spacestation.c.s:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/spacestation.c.s
.PHONY : spacestation.c.s

util.obj: util.c.obj

.PHONY : util.obj

# target to build an object file
util.c.obj:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/util.c.obj
.PHONY : util.c.obj

util.i: util.c.i

.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s

.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) -f CMakeFiles/HIB.dir/build.make CMakeFiles/HIB.dir/util.c.s
.PHONY : util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... HIB.vpk"
	@echo "... HIB.self"
	@echo "... HIB"
	@echo "... bullet.obj"
	@echo "... bullet.i"
	@echo "... bullet.s"
	@echo "... display.obj"
	@echo "... display.i"
	@echo "... display.s"
	@echo "... enemy.obj"
	@echo "... enemy.i"
	@echo "... enemy.s"
	@echo "... gui.obj"
	@echo "... gui.i"
	@echo "... gui.s"
	@echo "... input.obj"
	@echo "... input.i"
	@echo "... input.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... ship.obj"
	@echo "... ship.i"
	@echo "... ship.s"
	@echo "... spacestation.obj"
	@echo "... spacestation.i"
	@echo "... spacestation.s"
	@echo "... util.obj"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

